{% set version = "0.5.63" %}

package:
  name: eppy-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/eppy/eppy-{{ version }}.tar.gz
  sha256: 40277bf4b3e0978311009d47fcb2ff0faf1a24694ed0640c4d5718a787d26c04

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - munch >=2.0.2
    - decorator >=4.0.10
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - eppy
    - eppy.modeleditor

about:
  home: https://github.com/santoshphilip/eppy
  summary: Scripting language for E+ idf files, and E+ output files
  license: MIT
  license_file: LICENSE
  doc_url: https://eppy.readthedocs.io/
  dev_url: https://github.com/santoshphilip/eppy

extra:
  recipe-maintainers:
    - airallergy
